name: "Static Analysis"

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    static-analysis-phpstan:
        name: Static Analysis (psalm)
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - 8.2

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}

            - name: Install dependencies with composer
              run: composer install --no-interaction --no-progress --no-suggest

            - name: Run a static analysis
              run: ./vendor/bin/psalm
